apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: user-service
commonLabels:
  app: api

resources:
- ../base
- ingress.yaml
- secret-provider-class.yaml

patches:
- path: deployment.yaml
- path: sa.yaml
- path: job.yaml

images:
- name: user-service
  newName: 974860574511.dkr.ecr.eu-west-1.amazonaws.com/user-service
  newTag: 0.1.0
